name: "Continue Publish Action"
description: "Publish a new version of your Continue assistant/block(s)"
inputs:
  paths:
    description: "The path or glob pattern of `.yaml` files to publish. The name of the file will be used as the assistant/block slug (excluding the `.yaml` extension)"
    required: true
  owner-slug:
    description: "The slug of the owner of the assistant/block(s) to publish"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  is-assistant:
    description: "Whether the assistant/block is an assistant"
    required: false
    default: "false"
  visibility:
    description: "The visibility of the assistant/block (public, private, or organization)"
    required: false
    default: "public"
  continue-api-domain:
    description: "The domain of the Continue platform to publish to. For internal testing."
    required: false
    default: "api.continue.dev"

runs:
  using: "node20"
  main: "index.js"
