name: "Continue Publish Action"
description: "Publish a new version of your Continue package"
inputs:
  slug:
    description: "The slug of the package to publish"
    required: true
  filepath:
    description: "The path to your package's YAML definition file"
    required: true
  continue-api-domain:
    description: "The domain of the Continue platform to publish to. For internal testing."
    required: false
    default: "api.continue.dev"
  api-key:
    description: "API key for authentication"
    required: false
runs:
  using: "node20"
  main: "index.js"
